### ISSUE TITLE
Error formatting hides the very helpful validator messages

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-python#44]
When supplying a too-large `limit=40` in #43 , `yelp-python` printed a stacktrace:
```
$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 25, in <module>
    response = client.search_by_coordinates(lat, lng, **params)
  File "/nail/home/kmitton/pg/other/yelp-python/yelp/endpoint/search.py", line 118, in search_by_coordinates
    self.client._make_request(SEARCH_PATH, url_params)
  File "/nail/home/kmitton/pg/other/yelp-python/yelp/client.py", line 48, in _make_request
    return self._make_connection(signed_url)
  File "/nail/home/kmitton/pg/other/yelp-python/yelp/client.py", line 54, in _make_connection
    self._error_handler.raise_error(error)
  File "/nail/home/kmitton/pg/other/yelp-python/yelp/errors.py", line 99, in raise_error
    response
yelp.errors.InvalidParameter
```

The actual error response was:
```
{u'error': {u'field': u'limit', u'text': u'One or more parameters are invalid in request', u'description': u'Limit maximum is 20', u'id': u'INVALID_PARAMETER'}}
```

We should really print more of that error message!

**Comment by mittonk** [comment]
This needs a version number bump and other release work, re-opening.
