### ISSUE TITLE
client.search_by_coordinates resulting in invalid_signature error though the 'Consumer Key', 'Secret', 'Token', 'Token Secret' are correct

### ISSUE THREAD

**Issue by arvindadari** [Yelp/yelp-python#56]

**Comment by mittonk** [comment]
@arvindadari : What's the full error output (either paste it here, or use a gist)?  That may have some more details.

**Comment by arvindadari** [comment]
@mittonk : Below is the detailed error. Thanks in advance.
Requested to yelp for a particular restaurant with yelp-python api passing following parameters 

'Consumer Key', 'Secret', 'Token', 'Token Secret' --- all are perfectly given.

Request:
params = {"term": restaurant_search_name, "radius_filter":100}
result = client.search_by_coordinates(restaurant_latitude, restaurant_longitude, **params)

Error which I received :
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/ubuntu/qt/api/factualviewset.py", line 95, in getPlaceId
    result = client.search_by_coordinates(lat, longi, **params)
  File "/usr/local/lib/python3.4/dist-packages/yelp/endpoint/search.py", line 118, in search_by_coordinates
    self.client._make_request(SEARCH_PATH, url_params)
  File "/usr/local/lib/python3.4/dist-packages/yelp/client.py", line 48, in _make_request
    return self._make_connection(signed_url)
  File "/usr/local/lib/python3.4/dist-packages/yelp/client.py", line 54, in _make_connection
    self._error_handler.raise_error(error)
  File "/usr/local/lib/python3.4/dist-packages/yelp/errors.py", line 107, in raise_error
    response
yelp.errors.InvalidSignature: {'id': 'INVALID_SIGNATURE', 'text': 'Signature was invalid', 'msg': 'Bad Request', 'code': 400}

**Comment by dan98765** [comment]
API Authentication format has changed since this was filed. I created a new issue https://github.com/Yelp/yelp-python/issues/62 to switch this clientlib to eliminate the old authentication scheme, which will obviate this issue.
